from tools import *

# Config

# FSEQ DIR
FSEQ_DIR = ''

# SACN RECEIVER
RECEIVER_IP = "192.168.1.10"
RECEIVER_UNIVERSES = 3
RECEIVER_FPS = 40

# OSC Server IP
SERVER_IP = "127.0.0.1"
SERVER_PORT = 6005
# UDP Message filter
UDP_FILTER = "/leds/*"

# ANIMATION DEFAULTS
ANIMATION_TI = 5000
ANIMATION_WAIT = 5000
ANIMATION_TO = 5000
ANIMATION_AUDIO = False
ANIMATION_DYN = False
ANIMATION_MAX = 255
ANIMATION_RESOLUTION = 255

ANIMATION_DEFAULTS = {
    'ti': ANIMATION_TI,
    'wait': ANIMATION_WAIT,
    'to': ANIMATION_TO,
    'audio': ANIMATION_AUDIO,
    'dynamic': ANIMATION_DYN
}

ANIMATION_CHANNEL_COUNT = 510

# AUDIO SETTINGS
AUDIO_RESOLUTION = 255
AUDIO_MIN_EFFECT = 0.3
AUDIO_MAX_EFFECT = 1
AUDIO_MAX_TEST = 6000
AUDIO_MAX_TEST_UPDATE = True
